---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by doomsdayrs.
--- DateTime: 1/16/20 9:25 PM
---

function newNovelPage()
    return luajava:newinstance("com.github.doomsdayrs.api.shosetsu.services.core.objects.NovelPage")
end

local baseURL = "https://bestlightnovel.com"

function getID()
    return 5
end

function getName()
    return "BestLightNovel"
end

function getImageURL()
    return "None"
end

function getLatestURL(page)
    i = page
    if i <= 0 then
        i = 1
    end
    return baseURL .. "/novel_list?type=latest&category=all&state=all&page=" .. i
end

function getNovelPassage(document)
    elements = document:selectFirst("div.vung_doc"):select("p")
    print(elements:size())
    if  elements:size()> 0 then
        passage = ""
        for i = 0, elements:size()-1, 1 do
            passage = passage .. elements:get(i):text() .. "\n"
        end
        return passage
    else
        return "NOT YET TRANSLATED"
    end
end


function parseNovel(document)
    novelPage = newNovelPage()
    return novelPage
end

function getSearchString(query)
     return baseURL .. "/search_novels/" .. string.gsub(query," ","_")
end

