require("luajava")
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by doomsdayrs.
--- DateTime: 1/16/20 9:25 PM
---

function newNovelPage()
    return luajava.newInstance("com.github.doomsdayrs.api.shosetsu.services.core.objects.NovelPage")
end

function ArrayList()
    return luajava.newInstance("java.util.ArrayList")
end

function StringArray()
    return luajava.newInstance("com.github.doomsdayrs.api.shosetsu.extensions.lang.en.StringArrays")
end

function NovelStatus()

end

local baseURL = "https://bestlightnovel.com"

function getID()
    return 5
end

function getName()
    return "BestLightNovel"
end

function getImageURL()
    return "None"
end

function getLatestURL(page)
    i = page
    if i <= 0 then
        i = 1
    end
    return baseURL .. "/novel_list?type=latest&category=all&state=all&page=" .. i
end

function getNovelPassage(document)
    elements = document:selectFirst("div.vung_doc"):select("p")
    print(elements:size())
    if elements:size() > 0 then
        passage = ""
        for i = 0, elements:size() - 1, 1 do
            passage = passage .. elements:get(i):text() .. "\n"
        end
        return passage
    else
        return "NOT YET TRANSLATED"
    end
end

function parseNovel(document)
    novelPage = newNovelPage()
    -- Image
    element = document:selectFirst("div.truyen_info_left")
    novelPage:setImageURL(element:selectFirst("img"):attr("src"))

    -- Bulk data
    element = document:selectFirst("ul.truyen_info_right")
    elements = element:select("li")
    subElement = nil
    subElements = nil
    strings = ArrayList()
    for i = 0, elements:size() - 1, 1 do
        e = elements:get(i)
        if i == 0 then
            novelPage:setTitle(e:selectFirst("h1"):text())
        elseif i == 1 then
            strings = StringArray()
            subElements = e:select("a")
            strings:setSize(subElements:size())
            for y = 0, subElements:size() - 1, 1 do
                strings:setPosition(y, subElements:get(y):text())
            end
            novelPage:setAuthors(strings:getStrings())
        elseif i == 2 then
            strings = StringArray()
            subElements = e:select("a")
            strings:setSize(subElements:size())
            for y = 0, subElements:size() - 1, 1 do
                strings:setPosition(y, subElements:get(y):text())
            end
            novelPage:setGenres(strings:getStrings())
        elseif i == 3 then
            subElement = e:select("a")
            text = subElement:text()
            if text == "" then
                novelPage:setStatus()
            elseif text == "" then
                novelPage:setStatus()
            else
            end
        end
    end
    return novelPage
end

function getSearchString(query)
    return baseURL .. "/search_novels/" .. string.gsub(query, " ", "_")
end

