-- {"id":2,"ver":"3.0.0","libVer":"1.0.0","author":"Doomsdayrs","dep":["Madara>=2.0.0"]}

return Require("Madara")("https://boxnovel.com", {
	id = 2,
	name = "BoxNovel",
	imageURL = "https://github.com/shosetsuorg/extensions/raw/dev/icons/BoxNovel.png",
	genres = {
		"Action",
		"Adventure",
		"Comedy",
		"Drama",
		"Ecchi",
		"Fantasy",
		"Gender Bender",
		"Harem",
		"Historical",
		"Horror",
		"Josei",
		"Martial Arts",
		"Mature",
		"Mecha",
		"Mystery",
		"Psychological",
		"Romance",
		"School Life",
		"Sci-fi",
		"Seinen",
		"Shoujo",
		"Shounen",
		"Slice of Life",
		"Smut",
		"Sports",
		"Supernatural",
		"Tragedy",
		"Wuxia",
		"Xianxia",
		"Xuanhuan",
		"Yaoi"
	},
	latestNovelSel = "div.col-xs-12.col-md-6"
})
