-- {"id":173,"ver":"2.0.0","libVer":"1.0.0","author":"TechnoJo4","dep":["Madara>=2.0.0"]}

return Require("Madara")("https://foxaholic.com", {
	id = 173,
	name = "Foxaholic",
	imageURL = "https://github.com/shosetsuorg/extensions/raw/dev/icons/Foxaholic.png",
	genres = {
		"Action",
		"Adventure",
		"BG",
		"BL",
		"Comedy",
		"Drama",
		"Ecchi",
		"Fantasy",
		"Gender Bender",
		"GL",
		"Harem",
		"Historical",
		"Horror",
		"Isekai",
		"Josei",
		"Martial Arts",
		"Mature",
		"Mecha",
		"Modern",
		"Mystery",
		"Psychological",
		"Rebirth",
		"Romance",
		"School Life",
		"Sci-fi",
		"Seinen",
		"Shoujo",
		"Slice of Life",
		"Supernatural",
		"Thai Novel",
		"Tragedy",
		"Transmigration",
		"Wuxia",
		"Xianxia",
		"Xuanhuan",
		chinese = "Chinese Novel",
		japanese = "Japanese Novels",
		original = "Original Novel",
	},
	doubleLoadChapters = true,
	latestNovelSel = "div.col-6",
	novelPageTitleSel = "h1"
})
