-- {"id":4221,"ver":"2.3.1","libVer":"1.0.0","author":"MechTechnology","dep":["Madara>=2.3.0"]}

return Require("Madara")("https://mysticalmerries.com", {
	id = 4221,
	name = "MysticalMerries",
	imageURL = "https://github.com/MechTechnology/extensions/raw/dev/icons/MysticalMerries.png",
	chaptersScriptLoaded = false,
	chaptersListSelector= "li.wp-manga-chapter.free-chap",
	novelListingURLPath = "genre/korean-novel",
	shrinkURLNovel = "series",

	genres = {
			"Action",
			"Adaptation",
			"Adventure",
			"Battle of Wits",
			"bilibili",
			"BL",
			"Campus",
			"CEO",
			["chinese-novel"] = "Chinese Novel",
			"Comedy",
			"Crossdressing",
			"Detective",
			"Drama",
			"Dropped",
			"Family",
			"Fantasy",
			"Gender Bender",
			"Girls",
			"GL",
			"Historical",
			"Horror",
			"Isekai",
			["korean-novel"] = "Korean Novel",
			"Manga",
			"Manhua",
			"Manhwa",
			["modern-romance"] = "Modern Romance",
			"Mystery",
			["office-workers"] = "Office Workers",
			["pilot-novel"] = "Pilot Novel Workers",
			"R15",
			"R19",
			"Regression",
			"Regression",
			"Reincarnation",
			"Revenge",
      ["romance-fantasy"] = "Romance Fantasy",
      ["school-of-life"] = "School Life",
			"Sci-fi",
			["slice-of-life"] = "Slice of Life",
			["slow-burn"] = "Slow Burn",
			"Smut",
			"Supernatural",
			"Teen",
			"Urban",
			["OnGoing"] = "Ongoing",
			["Complete"] = "Completed"
	}
})
