-- {"id":7619416,"ver":"1.0.0","libVer":"1.0.0","author":"AbhiTheModder","dep":["Madara>=2.2.0"]}
return Require("Madara")("https://novel-gate.com", {
	id = 7619416,
	name = "Novel-Gate",
	imageURL = "https://novel-gate.com/wp-content/uploads/2017/10/logo4small.png",

	genres = {
		"Action",
		"Adventure",
		"Comedy",
		"Drama",
		"Ecchi",
		"Fantasy",
		"Gender Bender",
		"Harem",
		"Historical",
		"Horror",
		"Josei",
		"Martial Arts",
		"Mature",
		"Mecha",
		"Mystery",
		"Psychological",
		"Romance",
		"School Life",
		"Sci-fi",
		"Seinen",
		"Shoujo",
		"Shounen",
		"Slice of Life",
		"Smut",
		"Sports",
		"Supernatural",
		"Tragedy",
		"Wuxia",
		"Xianxia",
		"Xuanhuan",
		"Yaoi"
	}
})
