-- {"id":4223,"ver":"1.0.3","libVer":"1.0.0","author":"MechTechnology","dep":["Madara>=2.3.0"]}

return Require("Madara")("https://reaperscans.com", {
	id = 4223,
	name = "Reaper Scans",
	imageURL = "https://github.com/shosetsuorg/extensions/raw/dev/icons/ReaperScans.png",
	chaptersScriptLoaded = false,
	chaptersListSelector= "li.wp-manga-chapter.free-chap",
	latestNovelSel = ".col-6.col-md-3.badge-pos-2",
	novelListingURLPath = "all-series/novels",
	shrinkURLNovel = "series",
	searchHasOper = true,

	genres = {
		"Action",
		"Adult",
		"Adventure",
		"Comedy",
		"Crime",
		"Drama",
		"Ecchi",
		"Fantasy",
		"Harem",
		"Historical",
		"Horror",
		"Isekai",
		"Manhua",
		"Manhwa",
		"Martial Arts",
		"Mature",
		"Mecha",
		"Mystery",
		"Novel",
		"Psychological",
		"Romance",
		"School Life",
		"Sci-fi",
		"Seinen",
		"Shoujo",
		"Shounen",
		["slice-of-life"] = "Slice of Life",
		"Sports",
		"Supernatural",
		"Tragedy",
		["complete"] = "Completed",
		["on-going"] = "Ongoing",
		"Canceled",
		"On Hold",
		"On Hold",
	}
})
