-- {"id":586,"ver":"1.0.1","libVer":"1.0.0","author":"TechnoJo4","dep":["Madara>=1.1.0"]}

return Require("Madara")("https://vipnovel.com", {
	id = 586,
	name = "VipNovel",
	imageURL = "https://github.com/shosetsuorg/extensions/raw/dev/icons/VipNovel.png",
	novelListingURLPath = "vipnovel",
	shrinkURLNovel = "vipnovel",
	genres = {
		"Action",
		"Adult",
		"Adventure",
		"Boy Love",
		"Comedy",
		"Drama",
		"Ecchi",
		"Fantasy",
		"Gender Bender",
		"Harem",
		"Historical",
		"Horror",
		"Josei",
		"LGBT+",
		"Martial Arts",
		"Mature",
		"Mecha",
		"Mystery",
		"Psychological",
		"Romance",
		"School Life",
		"Sci-fi",
		"Seinen",
		"Shoujo",
		"Shounen",
		"Slice of Life",
		"Smut",
		"Sports",
		"Supernatural",
		"Tragedy",
		"Video Games",
		"Wuxia",
		"Xianxia",
		"Xuanhuan",
		"Yaoi",
		"Yuri"
	}
})
