-- {"id":4226,"ver":"1.0.3","libVer":"1.0.0","author":"MechTechnology","dep":["Madara>=2.3.2"]}

return Require("Madara")("https://Wonpress.io", {
	id = 4226,
	name = "Wonpress",
	imageURL = "https://github.com/shosetsuorg/extensions/raw/dev/icons/Wonpress.png",
	novelListingURLPath = "series",
	shrinkURLNovel = "series",
	latestNovelSel = "div.col-6.col-md-3",

	genres = {
		"Action",
		"Adult",
		"Adventure",
		"Comedy",
		"Dark",
		"Drama",
		"Fantasy",
		"Harem",
		"Historical",
		"Horror",
		"Isekai",
		"Josei",
		"Light Novel",
		"Manhua",
		"Manhwa",
		"Martial Arts",
		"Mature",
		"Mystery",
		"Psychological",
		"Romance",
		"School Life",
		"Seinen",
		"Shoujo",
		"Shounen",
		"Supernatural",
		"Thriller",
		"Tragedy",
		"Virtual Reality",
		"Xuanhuan",
		"Canceled",
		"On Hold",
		["on-going"] = "Ongoing",
		["complete"] = "Completed",
		["slice-of-life"] = "Slice of Life",
	}
})
