-- {"id":4225,"ver":"1.0.3","libVer":"1.0.0","author":"MechTechnology","dep":["Madara>=2.3.2"]}

return Require("Madara")("https://ZinNovel.com", {
	id = 4225,
	name = "ZinNovel",
	imageURL = "https://github.com/shosetsuorg/extensions/raw/dev/icons/ZinNovel.png",
	novelListingURLPath = "manga",
	shrinkURLNovel = "manga",
	searchHasOper = true,

	genres = {
		"Action",
		"Adult",
		"Adventure",
		"Anime",
		"Cartoon",
		"Comedy",
		"Comic",
		"Cooking",
		"Detective",
		"Doujinshi",
		"Drama",
		"Ecchi",
		"Fantasy",
		"Game",
		"Gender Bender",
		"Harem",
		"Historical",
		"Horror",
		"Isekai",
		"Josei",
		"Live action",
		"Lolicon",
		"Magical Realism",
		"Manga",
		"Manhua",
		"Manhwa",
		"Martial Arts",
		"Mature",
		"Mecha",
		"Mystery",
		"One shot",
		"Psychological",
		"Reincarnation",
		"Romance",
		"School Life",
		"Sci-fi",
		"Seinen",
		"Shoujo",
		"Shoujo Ai",
		"Shounen",
		"Shounen Ai",
		["slice-of-life"] = "Slice of Life",
		"Smut",
		"Soft Yaoi",
		"Soft Yuri",
		"Sports",
		"Supernatural",
		"Tragedy",
		"Video Games",
		"Webtoon",
		"Wuxia",
		"Xianxia",
		"Xuanhuan",
		"Yaoi",
		["complete"] = "Completed",
		["on-going"] = "Ongoing",
		"Canceled",
		"On Hold",
	}
})
