-- {"id":2,"version":"2.0.0","author":"Doomsdayrs","repo":""}

return Require("Madara")("https://boxnovel.com", {
    id = 2,
    name = "BoxNovel",
    imageURL = "https://boxnovel.com/wp-content/uploads/2018/04/BoxNovel-1.png",
    genres = {
        CheckboxFilter(1, "Action"),
        CheckboxFilter(2, "Adventure"),
        CheckboxFilter(3, "Comedy"),
        CheckboxFilter(4, "Drama"),
        CheckboxFilter(5, "Ecchi"),
        CheckboxFilter(6, "Fantasy"),
        CheckboxFilter(7, "Gender Bender"),
        CheckboxFilter(8, "Harem"),
        CheckboxFilter(9, "Historical"),
        CheckboxFilter(10, "Horror"),
        CheckboxFilter(11, "Josei"),
        CheckboxFilter(12, "Martial Arts"),
        CheckboxFilter(13, "Mature"),
        CheckboxFilter(14, "Mecha"),
        CheckboxFilter(15, "Mystery"),
        CheckboxFilter(16, "Psychological"),
        CheckboxFilter(17, "Romance"),
        CheckboxFilter(18, "School Life"),
        CheckboxFilter(19, "Sci-fi"),
        CheckboxFilter(20, "Seinen"),
        CheckboxFilter(21, "Shoujo"),
        CheckboxFilter(22, "Shounen"),
        CheckboxFilter(23, "Slice of Life"),
        CheckboxFilter(24, "Smut"),
        CheckboxFilter(25, "Sports"),
        CheckboxFilter(26, "Supernatural"),
        CheckboxFilter(27, "Tragedy"),
        CheckboxFilter(28, "Wuxia"),
        CheckboxFilter(29, "Xianxia"),
        CheckboxFilter(30, "Xuanhuan"),
        CheckboxFilter(31, "Yaoi")
    },
    latestNovelSel = "div.col-xs-12.col-md-6"
})
