-- {"id":2,"version":"2.0.0","author":"Doomsdayrs","repo":""}

return Require("Madara")("https://boxnovel.com", {
	id = 2,
	name = "BoxNovel",
	imageURL = "https://boxnovel.com/wp-content/uploads/2018/04/BoxNovel-1.png",
	genres = {
		CheckboxFilter("Action"),
		CheckboxFilter("Adventure"),
		CheckboxFilter("Comedy"),
		CheckboxFilter("Drama"),
		CheckboxFilter("Ecchi"),
		CheckboxFilter("Fantasy"),
		CheckboxFilter("Gender Bender"),
		CheckboxFilter("Harem"),
		CheckboxFilter("Historical"),
		CheckboxFilter("Horror"),
		CheckboxFilter("Josei"),
		CheckboxFilter("Martial Arts"),
		CheckboxFilter("Mature"),
		CheckboxFilter("Mecha"),
		CheckboxFilter("Mystery"),
		CheckboxFilter("Psychological"),
		CheckboxFilter("Romance"),
		CheckboxFilter("School Life"),
		CheckboxFilter("Sci-fi"),
		CheckboxFilter("Seinen"),
		CheckboxFilter("Shoujo"),
		CheckboxFilter("Shounen"),
		CheckboxFilter("Slice of Life"),
		CheckboxFilter("Smut"),
		CheckboxFilter("Sports"),
		CheckboxFilter("Supernatural"),
		CheckboxFilter("Tragedy"),
		CheckboxFilter("Wuxia"),
		CheckboxFilter("Xianxia"),
		CheckboxFilter("Xuanhuan"),
		CheckboxFilter("Yaoi")
	},
	latestNovelSel = "div.col-xs-12.col-md-6"
})
