-- {"id":2,"version":"2.0.0","author":"Doomsdayrs","repo":""}

return Require("Madara")("https://boxnovel.com", {
    id = 2,
    name = "BoxNovel",
    imageURL = "https://boxnovel.com/wp-content/uploads/2018/04/BoxNovel-1.png",
    genres = {
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Ecchi",
        "Fantasy",
        "Gender Bender",
        "Harem",
        "Historical",
        "Horror",
        "Josei",
        "Martial Arts",
        "Mature",
        "Mecha",
        "Mystery",
        "Psychological",
        "Romance",
        "School Life",
        "Sci-fi",
        "Seinen",
        "Shoujo",
        "Shounen",
        "Slice of Life",
        "Smut",
        "Sports",
        "Supernatural",
        "Tragedy",
        "Wuxia",
        "Xianxia",
        "Xuanhuan",
        "Yaoi"
    },
    latestNovelSel = "div.col-xs-12.col-md-6"
})
