-- {"id":173,"version":"1.0.0","author":"TechnoJo4","repo":""}

return Require("Madara")("https://foxaholic.com", {
	id = 173,
	name = "Foxaholic",
	imageURL = "https://foxaholic.com/wp-content/uploads/2019/12/images-1.png",
	genres = {
		CheckboxFilter(2, "Action"),
		CheckboxFilter(3, "Adventure"),
		CheckboxFilter(3, "BG"),
		CheckboxFilter(3, "BL"),
		CheckboxFilter(3, "Chinese Novel"),
		CheckboxFilter(3, "Comedy"),
		CheckboxFilter(3, "Drama"),
		CheckboxFilter(3, "Ecchi"),
		CheckboxFilter(3, "Fantasy"),
		CheckboxFilter(3, "Gender Bender"),
		CheckboxFilter(3, "GL"),
		CheckboxFilter(3, "Harem"),
		CheckboxFilter(3, "Historical"),
		CheckboxFilter(3, "Horror"),
		CheckboxFilter(3, "Isekai"),
		CheckboxFilter(3, "Japanese Novels"),
		CheckboxFilter(3, "Josei"),
		CheckboxFilter(3, "Martial Arts"),
		CheckboxFilter(3, "Mature"),
		CheckboxFilter(3, "Mecha"),
		CheckboxFilter(3, "Modern"),
		CheckboxFilter(3, "Mystery"),
		CheckboxFilter(3, "Original Novel"),
		CheckboxFilter(3, "Psychological"),
		CheckboxFilter(3, "Rebirth"),
		CheckboxFilter(3, "Romance"),
		CheckboxFilter(3, "School Life"),
		CheckboxFilter(3, "Sci-fi"),
		CheckboxFilter(3, "Seinen"),
		CheckboxFilter(3, "Shoujo"),
		CheckboxFilter(3, "Slice of Life"),
		CheckboxFilter(3, "Supernatural"),
		CheckboxFilter(3, "Thai Novel"),
		CheckboxFilter(3, "Tragedy"),
		CheckboxFilter(3, "Transmigration"),
		CheckboxFilter(3, "Wuxia"),
		CheckboxFilter(3, "Xianxia"),
		CheckboxFilter(3, "Xuanhuan")
	}
})
