-- {"id":173,"version":"1.0.0","author":"TechnoJo4","repo":""}

return Require("Madara")("https://foxaholic.com", {
	id = 173,
	name = "Foxaholic",
	imageURL = "https://foxaholic.com/wp-content/uploads/2019/12/images-1.png",
	genres = {
		"Action",
		"Adventure",
		"BG",
		"BL",
		"Comedy",
		"Drama",
		"Ecchi",
		"Fantasy",
		"Gender Bender",
		"GL",
		"Harem",
		"Historical",
		"Horror",
		"Isekai",
		"Josei",
		"Martial Arts",
		"Mature",
		"Mecha",
		"Modern",
		"Mystery",
		"Psychological",
		"Rebirth",
		"Romance",
		"School Life",
		"Sci-fi",
		"Seinen",
		"Shoujo",
		"Slice of Life",
		"Supernatural",
		"Thai Novel",
		"Tragedy",
		"Transmigration",
		"Wuxia",
		"Xianxia",
		"Xuanhuan",
		chinese = "Chinese Novel",
		japanese = "Japanese Novels",
		original = "Original Novel",
	}
})
