-- {"id":173,"version":"1.0.0","author":"TechnoJo4","repo":""}

return Require("Madara")("https://foxaholic.com", {
	id = 173,
	name = "Foxaholic",
	imageURL = "https://foxaholic.com/wp-content/uploads/2019/12/images-1.png",
	genres = {
		CheckboxFilter("Action"),
		CheckboxFilter("Adventure"),
		CheckboxFilter("BG"),
		CheckboxFilter("BL"),
		CheckboxFilter("Chinese Novel"),
		CheckboxFilter("Comedy"),
		CheckboxFilter("Drama"),
		CheckboxFilter("Ecchi"),
		CheckboxFilter("Fantasy"),
		CheckboxFilter("Gender Bender"),
		CheckboxFilter("GL"),
		CheckboxFilter("Harem"),
		CheckboxFilter("Historical"),
		CheckboxFilter("Horror"),
		CheckboxFilter("Isekai"),
		CheckboxFilter("Japanese Novels"),
		CheckboxFilter("Josei"),
		CheckboxFilter("Martial Arts"),
		CheckboxFilter("Mature"),
		CheckboxFilter("Mecha"),
		CheckboxFilter("Modern"),
		CheckboxFilter("Mystery"),
		CheckboxFilter("Original Novel"),
		CheckboxFilter("Psychological"),
		CheckboxFilter("Rebirth"),
		CheckboxFilter("Romance"),
		CheckboxFilter("School Life"),
		CheckboxFilter("Sci-fi"),
		CheckboxFilter("Seinen"),
		CheckboxFilter("Shoujo"),
		CheckboxFilter("Slice of Life"),
		CheckboxFilter("Supernatural"),
		CheckboxFilter("Thai Novel"),
		CheckboxFilter("Tragedy"),
		CheckboxFilter("Transmigration"),
		CheckboxFilter("Wuxia"),
		CheckboxFilter("Xianxia"),
		CheckboxFilter("Xuanhuan")
	}
})
