-- {"id":736,"version":"1.0.0","author":"Doomsdayrs","repo":""}

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by doomsdayrs.
--- DateTime: 1/25/20 3:30 PM
---

local baseURL = "https://kisslightnovels.info"

return Require("Madara")(baseURL, {
	id = 736,
	name = "KissLightNovels",
	baseURL = baseURL,
	imageURL = "https://kisslightnovels.info/wp-content/uploads/2017/10/kisslightnovels-logo.png",
	latestNovelSel = "div.col-6.col-md-3",
	novelPageTitleSel = "h1",
	genres = {
		CheckboxFilter(3, "17+"),
		CheckboxFilter(3, "Action"),
		CheckboxFilter(3, "Adventure"),
		CheckboxFilter(3, "Comedy"),
		CheckboxFilter(3, "Cooking"),
		CheckboxFilter(3, "Detective"),
		CheckboxFilter(3, "Doujinshi"),
		CheckboxFilter(3, "Drama"),
		CheckboxFilter(3, "Ecchi"),
		CheckboxFilter(3, "Fantasy"),
		CheckboxFilter(3, "Gender Bender"),
		CheckboxFilter(3, "Harem"),
		CheckboxFilter(3, "Historical"),
		CheckboxFilter(3, "Horror"),
		CheckboxFilter(3, "Hot Light Novel"),
		CheckboxFilter(3, "Josei"),
		CheckboxFilter(3, "Manhua"),
		CheckboxFilter(3, "Martial Arts"),
		CheckboxFilter(3, "Mature"),
		CheckboxFilter(3, "Mecha"),
		CheckboxFilter(3, "Mystery"),
		CheckboxFilter(3, "One shot"),
		CheckboxFilter(3, "Psychological"),
		CheckboxFilter(3, "Romance"),
		CheckboxFilter(3, "School Life"),
		CheckboxFilter(3, "Sci-fi"),
		CheckboxFilter(3, "Seinen"),
		CheckboxFilter(3, "Shoujo"),
		CheckboxFilter(3, "Shoujo Ai"),
		CheckboxFilter(3, "Shounen"),
		CheckboxFilter(3, "Shounen Ai"),
		CheckboxFilter(3, "Slice of Life"),
		CheckboxFilter(3, "Soft Yaoi"),
		CheckboxFilter(3, "Soft Yuri"),
		CheckboxFilter(3, "Sports"),
		CheckboxFilter(3, "Supernatural"),
		CheckboxFilter(3, "Tragedy"),
		CheckboxFilter(3, "Wuxia"),
		CheckboxFilter(3, "Xianxia"),
		CheckboxFilter(3, "Xuanhuan"),
		CheckboxFilter(3, "Yaoi"),
		CheckboxFilter(3, "Yuri")
	},
})
