-- {"id":736,"version":"1.0.0","author":"Doomsdayrs","repo":""}

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by doomsdayrs.
--- DateTime: 1/25/20 3:30 PM
---

local baseURL = "https://kisslightnovels.info"

return Require("Madara")(baseURL, {
	id = 736,
	name = "KissLightNovels",
	baseURL = baseURL,
	imageURL = "https://kisslightnovels.info/wp-content/uploads/2017/10/kisslightnovels-logo.png",
	latestNovelSel = "div.col-6.col-md-3",
	novelPageTitleSel = "h1",
	genres = {
		CheckboxFilter("17+"),
		CheckboxFilter("Action"),
		CheckboxFilter("Adventure"),
		CheckboxFilter("Comedy"),
		CheckboxFilter("Cooking"),
		CheckboxFilter("Detective"),
		CheckboxFilter("Doujinshi"),
		CheckboxFilter("Drama"),
		CheckboxFilter("Ecchi"),
		CheckboxFilter("Fantasy"),
		CheckboxFilter("Gender Bender"),
		CheckboxFilter("Harem"),
		CheckboxFilter("Historical"),
		CheckboxFilter("Horror"),
		CheckboxFilter("Hot Light Novel"),
		CheckboxFilter("Josei"),
		CheckboxFilter("Manhua"),
		CheckboxFilter("Martial Arts"),
		CheckboxFilter("Mature"),
		CheckboxFilter("Mecha"),
		CheckboxFilter("Mystery"),
		CheckboxFilter("One shot"),
		CheckboxFilter("Psychological"),
		CheckboxFilter("Romance"),
		CheckboxFilter("School Life"),
		CheckboxFilter("Sci-fi"),
		CheckboxFilter("Seinen"),
		CheckboxFilter("Shoujo"),
		CheckboxFilter("Shoujo Ai"),
		CheckboxFilter("Shounen"),
		CheckboxFilter("Shounen Ai"),
		CheckboxFilter("Slice of Life"),
		CheckboxFilter("Soft Yaoi"),
		CheckboxFilter("Soft Yuri"),
		CheckboxFilter("Sports"),
		CheckboxFilter("Supernatural"),
		CheckboxFilter("Tragedy"),
		CheckboxFilter("Wuxia"),
		CheckboxFilter("Xianxia"),
		CheckboxFilter("Xuanhuan"),
		CheckboxFilter("Yaoi"),
		CheckboxFilter("Yuri")
	},
})
