-- {"id":81,"version":"1.0.0","author":"Doomsdayrs"}
return Require("Madara")("https://noveltrench.com", {
	id = 81,
	name = "NovelTrench",
	imageURL = "https://noveltrench.com/wp-content/uploads/2019/08/transparent1.png",
	genres = {
		CheckboxFilter("Action"),
		CheckboxFilter("Adult"),
		CheckboxFilter("Adventure"),
		CheckboxFilter("Alchemy"),
		CheckboxFilter("Comedy"),
		CheckboxFilter("Cooking"),
		CheckboxFilter("Crafting"),
		CheckboxFilter("Drama"),
		CheckboxFilter("Ecchi"),
		CheckboxFilter("Fantasy"),
		CheckboxFilter("Female Protagonist"),
		CheckboxFilter("Game Elements"),
		CheckboxFilter("Gender Bender"),
		CheckboxFilter("Hamrem-Seeking Male Lead"),
		CheckboxFilter("Harem"),
		CheckboxFilter("Historical"),
		CheckboxFilter("Horror"),
		CheckboxFilter("Isekai"),
		CheckboxFilter("Josei"),
		CheckboxFilter("Kingdom Building"),
		CheckboxFilter("Magic sword and sorcery"),
		CheckboxFilter("Manhua"),
		CheckboxFilter("Manhwa"),
		CheckboxFilter("Martial Arts"),
		CheckboxFilter("Mature"),
		CheckboxFilter("Mecha"),
		CheckboxFilter("Modern Setting"),
		CheckboxFilter("Mystery"),
		CheckboxFilter("Political Intrigue"),
		CheckboxFilter("Psychological"),
		CheckboxFilter("Reincarnation"),
		CheckboxFilter("Romance"),
		CheckboxFilter("School Life"),
		CheckboxFilter("Sci-fi"),
		CheckboxFilter("Seinen"),
		CheckboxFilter("Shoujo"),
		CheckboxFilter("Shounen"),
		CheckboxFilter("Shounen Ai"),
		CheckboxFilter("Slice of Life"),
		CheckboxFilter("Smut"),
		CheckboxFilter("Sports"),
		CheckboxFilter("Supernatural"),
		CheckboxFilter("Superpowers"),
		CheckboxFilter("Swords"),
		CheckboxFilter("Swordsman"),
		CheckboxFilter("Thriller"),
		CheckboxFilter("Tragedy"),
		CheckboxFilter("Transported to Another World"),
		CheckboxFilter("Virtual Reality"),
		CheckboxFilter("War"),
		CheckboxFilter("Wuxia"),
		CheckboxFilter("Xianxia"),
		CheckboxFilter("Xuanhuan"),
		CheckboxFilter("Yaoi")
	},
	---@param table table
	appendToSearchFilters = function(table)
		table.insert(7, DropdownFilter("Genres Condition", { "OR (having one of selected genres)", "AND (having all selected genres" }))
		return table
	end,
	appendToSearchURL = function(url, table)
		return url .. "&op=" .. table[7]
	end,
	latestNovelSel = "div.col-12.col-md-4.badge-pos-1",
	novelPageTitleSel = "h1",
	novelListingURLPath = "manga"
})
