-- {"id":586,"version":"1.0.0","author":"TechnoJo4","repo":""}

return Require("Madara")("https://vipnovel.com", {
	id = 586,
	name = "VipNovel",
	imageURL = "http://vipnovel.com/wp-content/uploads/2017/10/coollogo_com-1630861.png",
	novelListingURLPath = "vipnovel",
	genres = {
		CheckboxFilter("Action"),
		CheckboxFilter("Adult"),
		CheckboxFilter("Adventure"),
		CheckboxFilter("Boy Love"),
		CheckboxFilter("Comedy"),
		CheckboxFilter("Drama"),
		CheckboxFilter("Ecchi"),
		CheckboxFilter("Fantasy"),
		CheckboxFilter("Gender Bender"),
		CheckboxFilter("Harem"),
		CheckboxFilter("Historical"),
		CheckboxFilter("Horror"),
		CheckboxFilter("Josei"),
		CheckboxFilter("LGBT+"),
		CheckboxFilter("Martial Arts"),
		CheckboxFilter("Mature"),
		CheckboxFilter("Mecha"),
		CheckboxFilter("Mystery"),
		CheckboxFilter("Psychological"),
		CheckboxFilter("Romance"),
		CheckboxFilter("School Life"),
		CheckboxFilter("Sci-fi"),
		CheckboxFilter("Seinen"),
		CheckboxFilter("Shoujo"),
		CheckboxFilter("Shounen"),
		CheckboxFilter("Slice of Life"),
		CheckboxFilter("Smut"),
		CheckboxFilter("Sports"),
		CheckboxFilter("Supernatural"),
		CheckboxFilter("Tragedy"),
		CheckboxFilter("Video Games"),
		CheckboxFilter("Wuxia"),
		CheckboxFilter("Xianxia"),
		CheckboxFilter("Xuanhuan"),
		CheckboxFilter("Yaoi"),
		CheckboxFilter("Yuri")
	}
})
