-- {"id":586,"version":"1.0.0","author":"TechnoJo4","repo":""}

return Require("Madara")("https://vipnovel.com", {
	id = 586,
	name = "VipNovel",
	imageURL = "http://vipnovel.com/wp-content/uploads/2017/10/coollogo_com-1630861.png",
	genres = {
		CheckBoxFilter(40, "Action"),
		CheckBoxFilter(41, "Adult"),
		CheckBoxFilter(42, "Adventure"),
		CheckBoxFilter(43, "Boy Love"),
		CheckBoxFilter(44, "Comedy"),
		CheckBoxFilter(45, "Drama"),
		CheckBoxFilter(46, "Ecchi"),
		CheckBoxFilter(47, "Fantasy"),
		CheckBoxFilter(48, "Gender Bender"),
		CheckBoxFilter(49, "Harem"),
		CheckBoxFilter(50, "Historical"),
		CheckBoxFilter(51, "Horror"),
		CheckBoxFilter(52, "Josei"),
		CheckBoxFilter(53, "LGBT+"),
		CheckBoxFilter(54, "Martial Arts"),
		CheckBoxFilter(55, "Mature"),
		CheckBoxFilter(56, "Mecha"),
		CheckBoxFilter(57, "Mystery"),
		CheckBoxFilter(58, "Psychological"),
		CheckBoxFilter(59, "Romance"),
		CheckBoxFilter(60, "School Life"),
		CheckBoxFilter(61, "Sci-fi"),
		CheckBoxFilter(62, "Seinen"),
		CheckBoxFilter(63, "Shoujo"),
		CheckBoxFilter(64, "Shounen"),
		CheckBoxFilter(65, "Slice of Life"),
		CheckBoxFilter(66, "Smut"),
		CheckBoxFilter(67, "Sports"),
		CheckBoxFilter(68, "Supernatural"),
		CheckBoxFilter(69, "Tragedy"),
		CheckBoxFilter(70, "Video Games"),
		CheckBoxFilter(71, "Wuxia"),
		CheckBoxFilter(72, "Xianxia"),
		CheckBoxFilter(73, "Xuanhuan"),
		CheckBoxFilter(74, "Yaoi"),
		CheckBoxFilter(75, "Yuri")
	},
	novelListingURLPath = "vipnovel"
})
