-- {"id":586,"version":"1.0.0","author":"TechnoJo4","repo":""}

return Require("Madara")("https://vipnovel.com", {
	id = 586,
	name = "VipNovel",
	imageURL = "http://vipnovel.com/wp-content/uploads/2017/10/coollogo_com-1630861.png",
	novelListingURLPath = "vipnovel",
	shrinkURLNovel = "vipnovel",
	genres = {
		CheckboxFilter(3,"Action"),
		CheckboxFilter(3,"Adult"),
		CheckboxFilter(3,"Adventure"),
		CheckboxFilter(3,"Boy Love"),
		CheckboxFilter(3,"Comedy"),
		CheckboxFilter(3,"Drama"),
		CheckboxFilter(3,"Ecchi"),
		CheckboxFilter(3,"Fantasy"),
		CheckboxFilter(3,"Gender Bender"),
		CheckboxFilter(3,"Harem"),
		CheckboxFilter(3,"Historical"),
		CheckboxFilter(3,"Horror"),
		CheckboxFilter(3,"Josei"),
		CheckboxFilter(3,"LGBT+"),
		CheckboxFilter(3,"Martial Arts"),
		CheckboxFilter(3,"Mature"),
		CheckboxFilter(3,"Mecha"),
		CheckboxFilter(3,"Mystery"),
		CheckboxFilter(3,"Psychological"),
		CheckboxFilter(3,"Romance"),
		CheckboxFilter(3,"School Life"),
		CheckboxFilter(3,"Sci-fi"),
		CheckboxFilter(3,"Seinen"),
		CheckboxFilter(3,"Shoujo"),
		CheckboxFilter(3,"Shounen"),
		CheckboxFilter(3,"Slice of Life"),
		CheckboxFilter(3,"Smut"),
		CheckboxFilter(3,"Sports"),
		CheckboxFilter(3,"Supernatural"),
		CheckboxFilter(3,"Tragedy"),
		CheckboxFilter(3,"Video Games"),
		CheckboxFilter(3,"Wuxia"),
		CheckboxFilter(3,"Xianxia"),
		CheckboxFilter(3,"Xuanhuan"),
		CheckboxFilter(3,"Yaoi"),
		CheckboxFilter(3,"Yuri")
	}
})
